    
dist: xenial

language: python

sudo: required

python:
    - "2.7"

services:
    - postgresql
    - redis-server

addons:
    postgresql: "10.4"

env:
    - CKANVERSION=2.8

install: bash bin/travis-build.bash

script: bash bin/travis-run.sh

after_success: coveralls